---
- name: Manage httpd.conf
  hosts: web
  become: true
  tasks:

    - name: Copy Apache configuration file
      ansible.builtin.copy:
        src: httpd.conf
        dest: /etc/httpd/conf/
        mode: '644'
      notify:
        - Restart_apache

  handlers:
    - name: Restart_apache
      ansible.builtin.service:
        name: httpd
        state: restarted
