---
theme: jekyll-theme-dinky
include:
  - "provisioner/README.md"
exclude:
  - "roles"
  - "provisioner/roles"
  - "provisioner/group_vars"
  - "provisioner/inventory"
  - "provisioner/tests"
  - "legacy-assets"
  - "provisioner/provision_lab.yml"
  - "provisioner/teardown_lab.yml"
  - "provisioner/workshop_specific"
  - "exercises/ansible_f5"
  - "exercises/ansible_config_as_code/answer_files/workshop_project/playbooks/"
kramdown:
  syntax_highlighter_opts:
    disable: true
