---
- name: Install packages for ripu pets
  ansible.builtin.package:
    name:
      - at
      - cockpit
      - cockpit-system
      - git
    state: present

- name: Enable and start cockpit console service
  ansible.builtin.service:
    name: cockpit.socket
    enabled: true
    state: started

- name: Enable and start atd
  ansible.builtin.service:
    name: atd.service
    enabled: true
    state: started

- name: Leapp custom actor repository
  ansible.builtin.yum_repository:
    name: leapp-supplements
    description: Leapp custom actors for workshop demo
    baseurl: https://people.redhat.com/bmader/leapp-supplements-demo/RHEL/$releasever/$basearch
    gpgcheck: false
    enabled: false

- name: Gather distribution and distribution_major_version facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - distribution
      - distribution_major_version

- name: Code block for sshd_config modification on RHEL7 nodes
  block:
    - name: Set PasswordAuthentication no in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"

    - name: restart ssh
      service:
        name: sshd
        state: restarted

    - name: Wait 400 seconds (using ansible.builtin.wait_for)
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        timeout: 400
        port: 22
      become: false
      vars:
        ansible_connection: local

  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version|int == 7
