---
- name: Make sure security workshop has password set is set to a correct value
  ansible.builtin.assert:
    that:
      - windows_password is defined
    msg: "windows_password must be set for security automation workshop"

- name: Install required roles
  community.general.ansible_galaxy_install:
    type: role
    requirements_file: "{{ role_path }}/files/security_requirements.yml"
    dest: ./workshop_specific/roles/
  register: required_role_loop_out
