---
- name: find ami for netapp
  amazon.aws.ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[netapp].owners }}"
    filters:
      name: "{{ ec2_info[netapp].filter }}"
      architecture: "{{ ec2_info[netapp].architecture }}"
  register: amis

- name: save ami for netapp
  set_fact:
    netapp_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: RHEL instance size list length
  ansible.builtin.debug:
    msg: "RHEL instance size list length: {{ ec2_info[rhel].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call Storage retry tasks include
  ansible.builtin.include_tasks: storage/storage_loop.yml
...
