---
- name: RHEL instance size list length
  ansible.builtin.debug:
    msg: "RHEL instance size list length: {{ ec2_info[rhel].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call RHEL retry tasks include
  ansible.builtin.include_tasks: devops/devops_loop.yml
...