---
- name: RIPU instance size list length
  ansible.builtin.debug:
    msg: "RIPU instance size list length: {{ ec2_info[rhel].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call RIPU retry tasks include
  ansible.builtin.include_tasks: ripu/ripu_loop.yml
...
