---
- name: Control cluster instance size list length
  ansible.builtin.debug:
    msg: "Attendance instance size list length: {{ ec2_info[control_type].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call control cluster retry tasks include
  ansible.builtin.include_tasks: instances/control_cluster/cluster_loop.yml
...
